// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQvzsmok3ZTbxB_o1wrhWgVAZbblvDmPo',
    appId: '1:859015279020:web:a844f0d4898f52f5380a09',
    messagingSenderId: '859015279020',
    projectId: 'gastosocr-c00b8',
    authDomain: 'gastosocr-c00b8.firebaseapp.com',
    storageBucket: 'gastosocr-c00b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_lZspeBgsR1YE0HgCcO49MZHsTWy6fjo',
    appId: '1:859015279020:android:c01930c0bbdae234380a09',
    messagingSenderId: '859015279020',
    projectId: 'gastosocr-c00b8',
    storageBucket: 'gastosocr-c00b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7eSMnvEDlXoiMW2DgaHEQ38dlDjFx9Ng',
    appId: '1:859015279020:ios:334a75afb802d191380a09',
    messagingSenderId: '859015279020',
    projectId: 'gastosocr-c00b8',
    storageBucket: 'gastosocr-c00b8.firebasestorage.app',
    iosClientId: '859015279020-2t1s3g2l5u02ie9im8s36tm9ka532bkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gastosCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7eSMnvEDlXoiMW2DgaHEQ38dlDjFx9Ng',
    appId: '1:859015279020:ios:334a75afb802d191380a09',
    messagingSenderId: '859015279020',
    projectId: 'gastosocr-c00b8',
    storageBucket: 'gastosocr-c00b8.firebasestorage.app',
    iosClientId: '859015279020-2t1s3g2l5u02ie9im8s36tm9ka532bkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gastosCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQvzsmok3ZTbxB_o1wrhWgVAZbblvDmPo',
    appId: '1:859015279020:web:6b7d317bbac74f4d380a09',
    messagingSenderId: '859015279020',
    projectId: 'gastosocr-c00b8',
    authDomain: 'gastosocr-c00b8.firebaseapp.com',
    storageBucket: 'gastosocr-c00b8.firebasestorage.app',
  );
}
